# Generated by Django 6.1 on 2026-08-20 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='الاسم الكامل')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('status', models.CharField(choices=[('lead', 'مهتم (Lead)'), ('active', 'زبون فعلي (Active)'), ('vip', 'زبون مميز (VIP)')], default='lead', max_length=20, verbose_name='حالة الزبون')),
                ('interest', models.CharField(blank=True, max_length=200, null=True, verbose_name='الاهتمامات / المنتجات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_details', models.TextField(verbose_name='تفاصيل الديكور / الطلبية')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ (دج)')),
                ('status', models.CharField(choices=[('pending', 'قيد التجهيز'), ('shipping', 'جاري التوصيل'), ('delivered', 'تم التسليم')], default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='crm.customer', verbose_name='الزبون')),
            ],
        ),
    ]
